### ISSUE TITLE
Page Working in the Context of the Current User | Bitrix24 REST API and Market Applications

### ISSUE THREAD

**Issue by sd012gfhkhhvh** [bitrix24/b24restdocs#4]
Lint to page: https://apidocs.bitrix24.com/api-reference/crest-php-sdk/using-in-users-context.html
The method is not working as it should be. It still returns the user data of the webhook creator instate of the current logged in user

**Comment by serg-vostrikov-bitrix** [comment]
well, it's not for webhooks, it's for local and mass-market applications, where B24 sends tokens of the current user into iframe or event handler. Local inbound webhook is like a timeless API password of the user who created this webhook. If you use this webhook to call REST API methods they always are considered as calls by this specific user
